# Generated by Django 5.2.14 on 2026-05-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('twitch', 'Twitch'), ('kick', 'Kick')], max_length=20)),
                ('channel_id', models.CharField(max_length=200)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.gang')),
            ],
        ),
    ]
