# Generated by Django 5.2.14 on 2026-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=20)),
                ('channel_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('gang_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
