# Generated by Django 5.2.14 on 2026-05-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_streamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='category',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('gang', 'Gang'), ('admin', 'Admin')], default='citizen', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamer',
            name='gang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streams.gang'),
        ),
    ]
